version: "3"
services:
  app1:
    build: ./app
  app2:
    build: ./app
  app3:
    build: ./app

  nginx:
    build: ./nginx
    ports:
      - "9090:9191"
    depends_on:
      - app1
      - app2
      - app3
